### ISSUE TITLE
Sync notebooks

### ISSUE THREAD

**Issue by JuanitoFatas** [JuanitoFatas/wb#1]
```yaml
workbook:
  sync:
    location: https://github.com/JuanitoFatas/workbooks
    command: "git add . && git commit -m "Update notebooks on 2018-09-25 19:10" && git push origin master"
```

```
wb sync
```

Sync all notes to designated location.
